/**
 * Holds constants used for action types.
 */
export default {
  FETCH_DIETARY_PROFILE_STARTED: 'FETCH_DIETARY_PROFILE_STARTED',
  FETCH_DIETARY_PROFILE_SUCCESS: 'FETCH_DIETARY_PROFILE_SUCCESS',
  FETCH_DIETARY_PROFILE_FAILURE: 'FETCH_DIETARY_PROFILE_FAILURE',
  FETCH_DIETARY_PROFILE_ENDED: 'FETCH_DIETARY_PROFILE_ENDED',

  UPDATE_DIETARY_PROFILE_STARTED: 'UPDATE_DIETARY_PROFILE_STARTED',
  UPDATE_DIETARY_PROFILE_SUCCESS: 'UPDATE_DIETARY_PROFILE_SUCCESS',
  UPDATE_DIETARY_PROFILE_FAILURE: 'UPDATE_DIETARY_PROFILE_FAILURE',
  UPDATE_DIETARY_PROFILE_ENDED: 'UPDATE_DIETARY_PROFILE_ENDED',

  USER_SIGN_IN_STARTED: 'USER_SIGN_IN_STARTED',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',
  USER_SIGN_IN_ENDED: 'USER_SIGN_IN_ENDED',

  // ToDo: Implement the service, reducer, and action creators for this action
  FETCH_PANTRY_STARTED: 'FETCH_PANTRY_STARTED',
  FETCH_PANTRY_SUCCESS: 'FETCH_PANTRY_SUCCESS',
  FETCH_PANTRY_FAILURE: 'FETCH_PANTRY_FAILURE',
  FETCH_PANTRY_ENDED: 'FETCH_PANTRY_ENDED',
};