/**
 * Holds constants used for action types.
 */
export default {
  FETCH_DIETARY_PROFILE_STARTED: 'FETCH_DIETARY_PROFILE_STARTED',
  FETCH_DIETARY_PROFILE_SUCCESS: 'FETCH_DIETARY_PROFILE_SUCCESS',
  FETCH_DIETARY_PROFILE_FAILURE: 'FETCH_DIETARY_PROFILE_FAILURE',

  UPDATE_DIETARY_PROFILE_STARTED: 'UPDATE_DIETARY_PROFILE_STARTED',
  UPDATE_DIETARY_PROFILE_SUCCESS: 'UPDATE_DIETARY_PROFILE_SUCCESS',
  UPDATE_DIETARY_PROFILE_FAILURE: 'UPDATE_DIETARY_PROFILE_FAILURE',

  USER_SIGN_IN_STARTED: 'USER_SIGN_IN_STARTED',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',

  FETCH_PANTRY_STARTED: 'FETCH_PANTRY_STARTED',
  FETCH_PANTRY_SUCCESS: 'FETCH_PANTRY_SUCCESS',
  FETCH_PANTRY_FAILURE: 'FETCH_PANTRY_FAILURE',

  SCANNING_RECEIPT_STARTED: 'SCANNING_RECEIPT_STARTED',
  SCANNING_RECEIPT_SUCCESS: 'SCANNING_RECEIPT_SUCCESS',
  SCANNING_RECEIPT_FAILURE: 'SCANNING_RECEIPT_FAILURE',

  UPDATE_PANTRY_STARTED: 'UPDATE_PANTRY_STARTED',
  UPDATE_PANTRY_SUCCESS: 'UPDATE_PANTRY_SUCCESS',
  UPDATE_PANTRY_FAILURE: 'UPDATE_PANTRY_FAILURE',

  FETCH_WEEKLY_GOALS_STARTED: 'FETCH_WEEKLY_GOALS_STARTED',
  FETCH_WEEKLY_GOALS_SUCCESS: 'FETCH_WEEKLY_GOALS_SUCCESS',
  FETCH_WEEKLY_GOALS_FAILURE: 'FETCH_WEEKLY_GOALS_FAILURE',

  CREATE_NEW_WEEKLY_GOAL_STARTED: 'CREATE_NEW_WEEKLY_GOAL_STARTED',
  CREATE_NEW_WEEKLY_GOAL_SUCCESS: 'CREATE_NEW_WEEKLY_GOAL_SUCCESS',
  CREATE_NEW_WEEKLY_GOAL_FAILURE: 'CREATE_NEW_WEEKLY_GOAL_FAILURE',

  UPDATE_GOAL_BY_ID_STARTED: 'UPDATE_GOAL_BY_ID_STARTED',
  UPDATE_GOAL_BY_ID_SUCCESS: 'UPDATE_GOAL_BY_ID_SUCCESS',
  UPDATE_GOAL_BY_ID_FAILURE: 'UPDATE_GOAL_BY_ID_FAILURE',

  COMPLETE_GOAL_BY_ID_STARTED: 'COMPLETE_GOAL_BY_ID_STARTED',
  COMPLETE_GOAL_BY_ID_SUCCESS: 'COMPLETE_GOAL_BY_ID_SUCCESS',
  COMPLETE_GOAL_BY_ID_FAILURE: 'COMPLETE_GOAL_BY_ID_FAILURE',

  RESET_GOALS_STARTED: 'RESET_GOALS_STARTED',
  RESET_GOALS_SUCCESS: 'RESET_GOALS_SUCCESS',
  RESET_GOALS_FAILURE: 'RESET_GOALS_FAILURE',

  DELETE_GOAL_BY_ID_STARTED: 'DELETE_GOAL_BY_ID_STARTED',
  DELETE_GOAL_BY_ID_SUCCESS: 'DELETE_GOAL_BY_ID_SUCCESS',
  DELETE_GOAL_BY_ID_FAILURE: 'DELETE_GOAL_BY_ID_FAILURE',
};