/**
 * Holds constants used for action types.
 */
export default {
  FETCH_DIETARY_PROFILE_STARTED: 'FETCH_DIETARY_PROFILE_STARTED',
  FETCH_DIETARY_PROFILE_SUCCESS: 'FETCH_DIETARY_PROFILE_SUCCESS',
  FETCH_DIETARY_PROFILE_FAILURE: 'FETCH_DIETARY_PROFILE_FAILURE',


  UPDATE_DIETARY_PROFILE_STARTED: 'UPDATE_DIETARY_PROFILE_STARTED',
  UPDATE_DIETARY_PROFILE_SUCCESS: 'UPDATE_DIETARY_PROFILE_SUCCESS',
  UPDATE_DIETARY_PROFILE_FAILURE: 'UPDATE_DIETARY_PROFILE_FAILURE',


  USER_SIGN_IN_STARTED: 'USER_SIGN_IN_STARTED',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',

  // ToDo: Implement the service, reducer, and action creators for this action
  FETCH_PANTRY_STARTED: 'FETCH_PANTRY_STARTED',
  FETCH_PANTRY_SUCCESS: 'FETCH_PANTRY_SUCCESS',
  FETCH_PANTRY_FAILURE: 'FETCH_PANTRY_FAILURE',

  SCANNING_RECEIPT_STARTED: 'SCANNING_RECEIPT_STARTED',
  SCANNING_RECEIPT_SUCCESS: 'SCANNING_RECEIPT_SUCCESS',
  SCANNING_RECEIPT_FAILURE: 'SCANNING_RECEIPT_FAILURE',

  UPDATE_PANTRY_STARTED: 'UPDATE_PANTRY_STARTED',
  UPDATE_PANTRY_SUCCESS: 'UPDATE_PANTRY_SUCCESS',
  UPDATE_PANTRY_FAILURE: 'UPDATE_PANTRY_FAILURE',

  // search recipes service states
  SEARCH_RECIPES_STARTED: 'SEARCH_RECIPES_STARTED',
  SEARCH_RECIPES_SUCCESS: 'SEARCH_RECIPES_SUCCESS',
  SEARCH_RECIPES_FAILURE: 'SEARCH_RECIPES_FAILURE',
};